# Generated by Django 5.1 on 2024-08-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("producer_country_name", models.CharField(max_length=200)),
                ("is_visible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.mark"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField(default=0, null=True)),
                ("json_data", models.JSONField(null=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.mark"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.model"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "mark", "json_data", "is_visible"],
                        name="search_part_name_7c5c35_idx",
                    ),
                    models.Index(
                        fields=["mark", "json_data", "is_visible"],
                        name="search_part_mark_id_a57f57_idx",
                    ),
                ],
            },
        ),
    ]
